### ISSUE TITLE
Multidimensional integration

### ISSUE THREAD

**Issue by MaxandreJ** [dextorious/NumericalIntegration.jl#16]
Thank you for your work on the package.

Multidimensional integration would be a good feature to have. Using the dims keyword argument as in the base function `sum`.

Best,
Maxandre

**Comment by dextorious** [comment]
Thanks for the suggestion. PRs are welcome, otherwise I'll try to get to it soon-ish.

**Comment by m-wells** [comment]
I've got a working n-dimensional trapezoidal integrator that could probably also be used to wrap the other methods as well.  As an example
```julia
using HCubature
using BenchmarkTools

X = -3:.01:3
Y = -5:.01:5
Z = -2:.02:2

A = Array{Float64}(undef,length(X),length(Y),length(Z))
f(x) = sin(x[1])+cos(x[2])+2x[3]

for (k,z) in enumerate(Z)
    for (j,y) in enumerate(Y)
        for (i,x) in enumerate(X)
            A[i,j,k] = f([x,y,z])
        end
    end
end

@btime trap(A,X,Y,Z)
@show trap(A,X,Y,Z)
@show hcubature(f, [-3,-5,-2], [3,5,2])
```
the result btw is
```julia
julia> include("trap1.jl")
  1.777 s (3219630 allocations: 5.65 GiB)
trap(A, X, Y, Z) = -46.02798161348153
hcubature(f, [-3, -5, -2], [3, 5, 2]) = (-46.02836518387838, 6.336969342740639e-7)
(-46.02836518387838, 6.336969342740639e-7)
```
I use `HCubature` as a way to verify that this method is actually returning the "correct" answer.  The number of allocations may seem like a a lot but keep in mind
```julia
julia> length(X)*length(Y)*length(Z)
120921801
```

If there is interest I could submit a PR (in the next few days).  If there is interest would you prefer calls of the form `integrate((x,y,z),A)` where `x,y,z` are `Vectors` or `Ranges`? I could use `NTuple` to on this syntax.  Currently I am using `Vararg` to dispatch.

**Comment by m-wells** [comment]
I've been playing with this and it seems like the best way to implement it would be to swap the positional arguments.  The reasoning is that the dimensional vectors are dispatched via `Varargs` which must be the last positional argument.

Essentially the calls will be of the form
```julia
integrate(y,x)
integrate(method,y,x)
integrate(Y,X1,X2,X3)
integrate(method,Y,X1,X2,X3)
```

**Comment by dextorious** [comment]
Thanks for your interest, I'd definitely like to see a PR and finally get this functionality into the package.

A few tentative comments on what you posted so far - I'm not sure we need the `Vararg` approach, `NTuple` might be sufficient. For now I'd say stick to the one you have implemented already, once the PR is up and I can test it we can try out both and see which is better. I definitely want to get the allocations down as close to zero as possible and optimize the code, but many of the allocations in your example came from heap allocating the input vector (`f([x,y,z])` instead of `f((x,y,z))`), so I'm not sure how much of a problem it's going to be.

My suggestion would be to submit a PR whenever you feel it's reasonable and we can finish it up together.

**Comment by m-wells** [comment]
I've got a PR (#17) up that is passing tests.  It might need some work on code coverage but it is ready for you to look at.

**Comment by m-wells** [comment]
@dextorious Do you have any thoughts on how it is currently implemented?

**Comment by dextorious** [comment]
Sorry for the delay, I've been pretty busy this week. Will be reviewing your PR tomorrow.

**Comment by dextorious** [comment]
I wasn't sure how to push to the PR directly, so I just merged it and pushed some changes on top of it. I managed to reduce the allocations by about 5x or so and improve the runtime performance a bit (20-30%). Unfortunately, until we get reliably stack allocated views, I don't see an easy way to eliminate all of the allocations without unreasonable effort (writing everything out by hand).

More generally, I'm pretty happy with the `NTuple` API because it preserves convention with respect to the other integration methods. Restoring the test coverage would be nice before doing a release, but otherwise I think this is ready for use.

**Comment by m-wells** [comment]
Excellent.  I don't have a lot of time to work on improving the test coverage but I'm glad we could get this merged in.

**Comment by francescoalemanno** [comment]
I just discovered this package, i'm interested in using N-dimensional integration, if i understood correctly that is still unreleased functionality right?
```
using NumericalIntegration
vx=range(0,1,length=200)
vy=range(0,2,length=200)
vz=range(0,3,length=300)
M=[x^2+y^2+z^2 for x=vx,y=vy,z=vz]
integrate((vx,vy,vz),M)
```

this bit of code return nothing atm on my julia installation.
for now i hacked the functionality myself in a few lines
[julia discourse](https://discourse.julialang.org/t/optimizing-multidimensional-discrete-trapezoidal-integral/24598/8)
but i think this package is much more optimized, so i look forward for the next release :+1: 

Thank you

**Comment by dextorious** [comment]
You can just do `]add NumericalIntegration#master` to get the unreleased version now. This package has no dependencies and gets fairly infrequent commits, so it should be quite safe. I still haven't written comprehensive tests for the N-dimensional integration, though, so in theory there could be a bug in there somewhere.
